# Nome da Aplicação
spring.application.name=inventory-service

# Porta
server.port=8081

# Banco de Dados
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventory_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:juju2001}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator (Saúde da Aplicação)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logs
logging.level.stockvision.inventory=DEBUG